# Generated by Django 4.2.13 on 2026-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('answer_length', models.IntegerField()),
            ],
            options={
                'db_table': 'blank_item',
            },
        ),
        migrations.CreateModel(
            name='FallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('target_time', models.FloatField()),
                ('fall_window', models.FloatField()),
            ],
            options={
                'db_table': 'fall_event',
                'ordering': ['target_time'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.IntegerField()),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('original_text', models.TextField()),
                ('blank_text', models.TextField()),
            ],
            options={
                'db_table': 'subtitle',
                'ordering': ['segment_id'],
            },
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('youtube_url', 'YouTube URL'), ('file', '파일 업로드'), ('private_url', '개인 링크')], max_length=20)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('fidget', '피젯스피너 모드'), ('rain', '집중호우 모드')], max_length=10)),
                ('ai_status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('done', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('ai_error_message', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
