# Generated by Django 4.2.13 on 2026-05-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tadac_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='tadac_sessions.videosession'),
        ),
        migrations.AddField(
            model_name='fallevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fall_events', to='tadac_sessions.videosession'),
        ),
        migrations.AddField(
            model_name='fallevent',
            name='subtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fall_events', to='tadac_sessions.subtitle'),
        ),
        migrations.AddField(
            model_name='blankitem',
            name='subtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='tadac_sessions.subtitle'),
        ),
    ]
