# Generated by Django 4.2.13 on 2026-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_rate', models.FloatField(default=0.0)),
                ('total_score', models.IntegerField(default=0)),
                ('max_combo', models.IntegerField(default=0)),
                ('typing_accuracy', models.FloatField(default=0.0)),
                ('quiz_correct', models.IntegerField(default=0)),
                ('quiz_total', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_result',
            },
        ),
    ]
