# Generated by Django 4.2.13 on 2026-05-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresult',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
