# Generated by Django 4.2.13 on 2026-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_learningresult_tab_switch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresult',
            name='study_duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
