# Generated by Django 4.2.13 on 2026-05-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_index', models.IntegerField()),
                ('trigger_time', models.FloatField()),
                ('segment_start', models.IntegerField()),
                ('segment_end', models.IntegerField()),
                ('question', models.TextField()),
                ('options_json', models.JSONField()),
                ('answer_index', models.IntegerField()),
                ('explanation', models.TextField()),
            ],
            options={
                'db_table': 'quiz',
                'ordering': ['quiz_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='analytics.learningresult')),
            ],
            options={
                'db_table': 'quiz_attempt',
            },
        ),
    ]
