# Generated by Django 4.2.13 on 2026-05-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('tadac_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='tadac_sessions.videosession'),
        ),
    ]
